### ISSUE TITLE
Fail to “python setup.py develop”

### ISSUE THREAD

**Issue by myxno** [Bob-cheng/CL-FusionAttack#5]
When I was “python setup.py develop”, I encountered an error message：
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/yeshunan/.conda/envs/new/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1900, in _run_ninja_build
    subprocess.run(
  File "/home/yeshunan/.conda/envs/new/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    setup(
  File "/home/yeshunan/.conda/envs/new/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in setup
    return distutils.core.setup(**attrs)
  File "/home/yeshunan/.conda/envs/new/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/yeshunan/.conda/envs/new/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/yeshunan/.conda/envs/new/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/yeshunan/.conda/envs/new/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/yeshunan/.conda/envs/new/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/yeshunan/.conda/envs/new/lib/python3.8/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/home/yeshunan/.conda/envs/new/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/yeshunan/.conda/envs/new/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/yeshunan/.conda/envs/new/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/yeshunan/.conda/envs/new/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/yeshunan/.conda/envs/new/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File "/home/yeshunan/.conda/envs/new/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/yeshunan/.conda/envs/new/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/yeshunan/.conda/envs/new/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/yeshunan/.conda/envs/new/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/home/yeshunan/.conda/envs/new/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/yeshunan/.conda/envs/new/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1573, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/yeshunan/.conda/envs/new/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

May I ask if you can help me solve this problem.In addition, I also encountered a similar problem when "mim install mmcv-full=1.4.0"
 ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/home/yeshunan/.local/lib/python3.11/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
          subprocess.run(
        File "/home/anaconda3/lib/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '39']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:
...
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmcv-full
  Running setup.py clean for mmcv-full
Failed to build mmcv-full
ERROR: Could not build wheels for mmcv-full, which is required to install pyproject.toml-based projects

So in the end, I used "mim install mmcv-full" and it intall 1.7.2

**Comment by zhanz5** [comment]
I have the same issue.

**Comment by Meoss** [comment]
I have the same issue.

**Comment by fwbut666** [comment]
I successfully downloaded mmcv-full=1.4.0, but I still can't install your custom library mmdet3d

**Comment by fwbut666** [comment]
I succeeded, the torch version given by the author cannot be installed, it is recommended to use **torch=1.10.1, cuda=11.3**, and the next installation method is the same

**Comment by noleti** [comment]
@fwbut666 we are running in same issues, can you provide a bit more details on how you got this to run earlier this year? which OS? which versions of torch/cuda/ installed how?
